ALTER TABLE "StorefrontTheme"
ADD COLUMN "maxInstallments" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN "cardInstallmentMonthlyRateBps" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "pixDiscountBps" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN "paymentFeeSource" TEXT NOT NULL DEFAULT 'MANUAL';
