#!/usr/bin/env bash

set -Eeuo pipefail

log() {
  printf '[backup] %s\n' "$*"
}

require_env() {
  local key="$1"
  if [[ -z "${!key:-}" ]]; then
    log "Missing required environment variable: ${key}"
    exit 1
  fi
}

github_api() {
  local method="$1"
  local url="$2"
  local data="${3:-}"

  if [[ -n "$data" ]]; then
    curl --silent --show-error --fail \
      -X "$method" \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer ${BACKUP_GITHUB_TOKEN}" \
      -H "Content-Type: application/json" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      "$url" \
      -d "$data"
    return
  fi

  curl --silent --show-error --fail \
    -X "$method" \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${BACKUP_GITHUB_TOKEN}" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "$url"
}

upload_to_github_release() {
  [[ "${BACKUP_GITHUB_ENABLED:-false}" == "true" ]] || return 0

  require_env BACKUP_GITHUB_TOKEN
  require_env BACKUP_GITHUB_REPOSITORY

  local repo="$BACKUP_GITHUB_REPOSITORY"
  local tag="${BACKUP_GITHUB_RELEASE_TAG:-nerdlingolab-backups}"
  local release_url="https://api.github.com/repos/${repo}/releases/tags/${tag}"
  local release_json

  if ! release_json="$(github_api GET "$release_url" 2>/dev/null)"; then
    log "GitHub release '${tag}' not found. Creating it."
    release_json="$(github_api POST "https://api.github.com/repos/${repo}/releases" "$(jq -nc \
      --arg tag "$tag" \
      --arg name "Nerdlingolab Backups" \
      --arg body "Encrypted automated backups generated by Nerdlingolab." \
      '{tag_name: $tag, name: $name, body: $body, draft: false, prerelease: false}')")"
  fi

  local release_id upload_url
  release_id="$(printf '%s' "$release_json" | jq -r '.id')"
  upload_url="$(printf '%s' "$release_json" | jq -r '.upload_url' | sed 's/{?name,label}//')"

  local asset_path asset_name existing_id
  for asset_path in "$ENCRYPTED_ARCHIVE" "$CHECKSUM_FILE"; do
    asset_name="$(basename "$asset_path")"
    existing_id="$(printf '%s' "$release_json" | jq -r --arg name "$asset_name" '.assets[]? | select(.name == $name) | .id' | head -n 1)"

    if [[ -n "$existing_id" ]]; then
      log "Replacing existing GitHub asset ${asset_name}"
      github_api DELETE "https://api.github.com/repos/${repo}/releases/assets/${existing_id}" >/dev/null
    fi

    log "Uploading ${asset_name} to GitHub Releases"
    curl --silent --show-error --fail \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer ${BACKUP_GITHUB_TOKEN}" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      -H "Content-Type: application/octet-stream" \
      --data-binary "@${asset_path}" \
      "${upload_url}?name=${asset_name}" >/dev/null
  done

  local keep_count="${BACKUP_GITHUB_RETENTION_COUNT:-30}"
  if [[ "$keep_count" =~ ^[0-9]+$ ]] && (( keep_count >= 0 )); then
    local release_with_assets backup_bases total_count prune_count
    release_with_assets="$(github_api GET "https://api.github.com/repos/${repo}/releases/${release_id}")"
    backup_bases="$(printf '%s' "$release_with_assets" | jq -r '
      [.assets[]
      | select(.name | endswith(".tar.gz.enc"))
      | { base: (.name | sub("\\.tar\\.gz\\.enc$"; "")), created_at }]
      | sort_by(.created_at)
      | .[].base
    ')"

    total_count="$(printf '%s\n' "$backup_bases" | awk 'NF' | wc -l | tr -d ' ')"
    prune_count=$(( total_count - keep_count ))

    if (( prune_count > 0 )); then
      printf '%s\n' "$backup_bases" | awk 'NF' | head -n "$prune_count" | while IFS= read -r old_base; do
        [[ -n "$old_base" ]] || continue
        log "Pruning old GitHub backup set ${old_base}"
        printf '%s' "$release_with_assets" | jq -r --arg base "$old_base" '
          .assets[]
          | select(.name | startswith($base))
          | .id
        ' | while IFS= read -r asset_id; do
          github_api DELETE "https://api.github.com/repos/${repo}/releases/assets/${asset_id}" >/dev/null
        done
      done
    fi
  fi
}

prune_local_archives() {
  local retention_days="${BACKUP_LOCAL_RETENTION_DAYS:-14}"
  local retention_count="${BACKUP_LOCAL_RETENTION_COUNT:-30}"

  if [[ "$retention_days" =~ ^[0-9]+$ ]]; then
    find /backups/archives -type f -mtime +"$retention_days" -delete 2>/dev/null || true
  fi

  if [[ "$retention_count" =~ ^[0-9]+$ ]] && (( retention_count > 0 )); then
    find /backups/archives -type f -name '*.tar.gz.enc' | sort | head -n "-${retention_count}" | while IFS= read -r old_archive; do
      [[ -n "$old_archive" ]] || continue
      rm -f "$old_archive" "${old_archive%.tar.gz.enc}.sha256"
    done
  fi

  find /backups/archives -type d -empty -delete 2>/dev/null || true
}

handle_error() {
  local exit_code="$1"
  local line_number="$2"
  local failed_command="$3"

  log "Backup failed at stage '${CURRENT_STAGE:-unknown}' with exit code ${exit_code}"
  printf 'stage=%s\ncommand=%s\nline=%s\nexit_code=%s\ntime=%s\n' \
    "${CURRENT_STAGE:-unknown}" \
    "$failed_command" \
    "$line_number" \
    "$exit_code" \
    "$(date --iso-8601=seconds)" >/backups/last-failure.txt 2>/dev/null || true
  exit "$exit_code"
}

export TZ="${TZ:-America/Sao_Paulo}"
CURRENT_STAGE="initializing"

DB_HOST="${BACKUP_DB_HOST:-postgres}"
DB_PORT="${BACKUP_DB_PORT:-5432}"
DB_NAME="${POSTGRES_DB:-nerdlingolab}"
DB_USER="${POSTGRES_USER:-nerdlingolab}"
DB_PASSWORD="${POSTGRES_PASSWORD:-}"
WORKSPACE_ROOT="${BACKUP_WORKSPACE_ROOT:-/workspace}"
SRV_ROOT="${BACKUP_SRV_ROOT:-/srv-data}"
MINIO_DATA_PATH="${BACKUP_MINIO_DATA_PATH:-${SRV_ROOT}/minio-data}"
CRITICAL_PATHS="${BACKUP_CRITICAL_PATHS:-.env,docker-compose.yml,prisma,data/shopify,ops}"

require_env POSTGRES_PASSWORD
require_env BACKUP_ENCRYPTION_PASSPHRASE
require_env DATA_ENCRYPTION_KEY

export PGPASSWORD="$DB_PASSWORD"

TIMESTAMP="$(date '+%Y-%m-%dT%H-%M-%S%z')"
ARCHIVE_DATE_PATH="$(date '+%Y/%m/%d')"
ARCHIVE_BASENAME="nerdlingolab-backup-${TIMESTAMP}"
RUN_ROOT="/tmp/${ARCHIVE_BASENAME}"
PAYLOAD_DIR="${RUN_ROOT}/payload"
ARCHIVE_DIR="/backups/archives/${ARCHIVE_DATE_PATH}"
BUNDLE_ARCHIVE="${RUN_ROOT}/${ARCHIVE_BASENAME}.tar.gz"
ENCRYPTED_ARCHIVE="${ARCHIVE_DIR}/${ARCHIVE_BASENAME}.tar.gz.enc"
CHECKSUM_FILE="${ARCHIVE_DIR}/${ARCHIVE_BASENAME}.sha256"
PAYLOAD_HASH_FILE="/backups/last-success-payload.sha256"

trap 'rm -rf "$RUN_ROOT"' EXIT
trap 'handle_error $? $LINENO "$BASH_COMMAND"' ERR

mkdir -p "$PAYLOAD_DIR" "$ARCHIVE_DIR"

CURRENT_STAGE="encryption-key-escrow"
log "Adding encrypted field key escrow to backup payload"
install -d -m 700 "$PAYLOAD_DIR/secrets"
{
  printf 'DATA_ENCRYPTION_KEY=%s\n' "$DATA_ENCRYPTION_KEY"
  if [[ -n "${FIELD_ENCRYPTION_KEY:-}" ]]; then
    printf 'FIELD_ENCRYPTION_KEY=%s\n' "$FIELD_ENCRYPTION_KEY"
  fi
} >"$PAYLOAD_DIR/secrets/field-encryption.env"
chmod 600 "$PAYLOAD_DIR/secrets/field-encryption.env"

CURRENT_STAGE="database-connectivity"
log "Checking database connectivity"
pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" >/dev/null

CURRENT_STAGE="database-dump"
log "Creating database dump"
pg_dump \
  --host "$DB_HOST" \
  --port "$DB_PORT" \
  --username "$DB_USER" \
  --dbname "$DB_NAME" \
  --restrict-key=nerdlingolabbackup \
  --format=plain \
  --clean \
  --if-exists \
  --no-owner \
  --no-privileges \
  --file "$PAYLOAD_DIR/database.sql"

CURRENT_STAGE="minio-archive"
log "Archiving MinIO data"
if [[ -d "$MINIO_DATA_PATH" ]]; then
  tar -C "$(dirname "$MINIO_DATA_PATH")" -czf "$PAYLOAD_DIR/minio-data.tar.gz" "$(basename "$MINIO_DATA_PATH")"
else
  log "MinIO data path not found: ${MINIO_DATA_PATH}. Creating empty marker."
  printf 'missing=%s\n' "$MINIO_DATA_PATH" >"$PAYLOAD_DIR/minio-data-missing.txt"
fi

CURRENT_STAGE="critical-files"
log "Archiving critical files"
IFS=',' read -r -a critical_items <<<"$CRITICAL_PATHS"
critical_existing=()
for item in "${critical_items[@]}"; do
  item="${item#"${item%%[![:space:]]*}"}"
  item="${item%"${item##*[![:space:]]}"}"
  [[ -n "$item" ]] || continue
  if [[ -e "${WORKSPACE_ROOT}/${item}" ]]; then
    critical_existing+=("$item")
  else
    log "Critical path missing, skipping: ${item}"
  fi
done

if (( ${#critical_existing[@]} > 0 )); then
  tar -C "$WORKSPACE_ROOT" -czf "$PAYLOAD_DIR/critical-files.tar.gz" "${critical_existing[@]}"
else
  printf 'No critical files found.\n' >"$PAYLOAD_DIR/critical-files-empty.txt"
fi

CURRENT_STAGE="manifest"
cat >"$PAYLOAD_DIR/manifest.json" <<JSON
{
  "app": "nerdlingolab",
  "createdAt": "$(date --iso-8601=seconds)",
  "appUrl": "${APP_URL:-}",
  "database": "${DB_NAME}",
  "minioDataPath": "${MINIO_DATA_PATH}",
  "criticalPaths": "${CRITICAL_PATHS}"
}
JSON

CURRENT_STAGE="change-detection"
log "Calculating stable payload hash"
payload_hash="$({
  printf 'database.sql\0'
  printf '%s\n' "$(sha256sum "$PAYLOAD_DIR/database.sql" | awk '{print $1}')"

  if [[ -d "$MINIO_DATA_PATH" ]]; then
    find "$MINIO_DATA_PATH" -type f -print0 \
      | sort -z \
      | while IFS= read -r -d '' file_path; do
          relative_path="${file_path#${MINIO_DATA_PATH}/}"
          file_hash="$(sha256sum "$file_path" | awk '{print $1}')"
          printf 'minio/%s %s\n' "$relative_path" "$file_hash"
        done
  else
    printf 'minio-missing %s\n' "$MINIO_DATA_PATH"
  fi

  for item in "${critical_existing[@]}"; do
    item_path="${WORKSPACE_ROOT}/${item}"
    if [[ -f "$item_path" ]]; then
      file_hash="$(sha256sum "$item_path" | awk '{print $1}')"
      printf 'critical/%s %s\n' "$item" "$file_hash"
    elif [[ -d "$item_path" ]]; then
      find "$item_path" -type f -print0 \
        | sort -z \
        | while IFS= read -r -d '' file_path; do
            relative_path="${file_path#${WORKSPACE_ROOT}/}"
            file_hash="$(sha256sum "$file_path" | awk '{print $1}')"
            printf 'critical/%s %s\n' "$relative_path" "$file_hash"
      done
    fi
  done

  if [[ -f "$PAYLOAD_DIR/secrets/field-encryption.env" ]]; then
    file_hash="$(sha256sum "$PAYLOAD_DIR/secrets/field-encryption.env" | awk '{print $1}')"
    printf 'secret/field-encryption.env %s\n' "$file_hash"
  fi
} | sha256sum | awk '{print $1}')"

if [[ "${BACKUP_SKIP_UNCHANGED:-true}" == "true" && -f "$PAYLOAD_HASH_FILE" ]]; then
  previous_hash="$(cat "$PAYLOAD_HASH_FILE" 2>/dev/null || true)"
  if [[ "$payload_hash" == "$previous_hash" ]]; then
    log "No data/config changes detected. Skipping archive upload."
    printf 'skipped_at=%s\npayload_hash=%s\n' "$(date --iso-8601=seconds)" "$payload_hash" >/backups/last-skipped.txt
    prune_local_archives
    exit 0
  fi
fi

CURRENT_STAGE="bundle"
log "Creating payload bundle"
tar -C "$PAYLOAD_DIR" -czf "$BUNDLE_ARCHIVE" .

CURRENT_STAGE="encrypt"
log "Encrypting archive"
openssl enc -aes-256-cbc -pbkdf2 -iter 200000 -salt \
  -in "$BUNDLE_ARCHIVE" \
  -out "$ENCRYPTED_ARCHIVE" \
  -pass env:BACKUP_ENCRYPTION_PASSPHRASE

sha256sum "$ENCRYPTED_ARCHIVE" | awk '{print $1}' >"$CHECKSUM_FILE"
printf '%s\n' "$payload_hash" >"$PAYLOAD_HASH_FILE"

CURRENT_STAGE="github-upload"
upload_to_github_release

CURRENT_STAGE="local-prune"
prune_local_archives

printf 'backup=%s\nchecksum=%s\npayload_hash=%s\n' "$ENCRYPTED_ARCHIVE" "$CHECKSUM_FILE" "$payload_hash" >/backups/last-success.txt
log "Backup completed: ${ENCRYPTED_ARCHIVE}"
